### ISSUE TITLE
[Bug] 퀴즈 결과 화면의 아이콘 로딩이 늦어 깜빡거리는 현상

### ISSUE THREAD

**Issue by luckylooky2** [luckylooky2/kanji_yomi#5]
![icon_flickering](https://github.com/user-attachments/assets/2a25e61d-4303-4d45-af24-b4e1fd75954e)

## Task Overview

퀴즈 결과 화면으로 이동할 때, 각각의 단어의 정답 여부를 표시한다. 각각의 단어는 애플리케이션 내부에 상태 값으로 저장되어 있고, 아이콘은 비동기적으로 프론트 서버로부터 가져온다. 이 때, 단어와 아이콘 로딩의 시간 차이 때문에 아이콘이 갑자기 생기는 것 같은 느낌이 든다. 사용자 입장에서는 자연스럽지 않기 때문에 이를 해결하고자 했다.

방법 1. quiz 페이지에 진입하면 필요한 이미지를 사전에 로딩한다.
- `<link rel="preload" href="/example.png" as="image" />`

방법 2. 결과 화면에서 이미지를 모두 로딩할 때까지 로딩 페이지를 보여준다.
방법 3. 이미지 플레이스홀더를 사용하여, 이미지를 로딩 중이라는 것을 알린다.

## Implementation Details
- **Feature**: 아이콘을 모두 로딩할 때까지 로딩 페이지를 보여주는 방법 2번을 선택했다.
- **Related Code Changes**: (File/Folder path)

## Acceptance Criteria
- [x] 결과 화면으로 이동할 때, 아이콘 이미지 로딩을 시작해야 한다.
- [x] 아이콘 로딩이 모두 완료될 때까지, 로딩 화면을 보여준다.
- [x] 아이콘 로딩 성공 여부와 관계없이 로딩이 완료되면 결과 화면을 보여주어야 한다.

## Version

v0.1.3
