### ISSUE TITLE
[Bug] quiz/answer API throttling 적용

### ISSUE THREAD

**Issue by luckylooky2** [luckylooky2/kanji_yomi#8]
## Task Overview
사용자가 퀴즈의 답을 맞추기 위해서 Enter 키를 길게 누를 때, 과도한 API 요청이 발생하여 서버에 과도한 부하가 될 수 있다. 쓰로틀링을 적용하여 과도한 API 요청을 줄이고자 했다.

## Implementation Details
- **Feature**: Throttling 적용을 통해 API 호출을 일정 시간 간격으로 제한하여 성능 최적화.
- **Related Code Changes**
  - 직접 구현하기보다 lodash 패키지를 사용

## Acceptance Criteria
- [x] Enter 키를 길게 누르더라도 API 요청이 설정된 쓰로틀 간격(예: 0.5초) 내에서 한 번만 발생한다.
- [x] Enter 키를 빠르게 여러 번 눌렀을 때도 API 요청이 적절히 제한된다.
- [x] 기존 기능(퀴즈 제출 및 응답 처리)에 영향을 미치지 않는다.
- [x] 쓰로틀링 해제 후에도 기존 동작이 정상적으로 작동한다.

## Version

v0.1.4
